spring.application.name=PayslipGenerator

spring.datasource.username=root
spring.datasource.password=Sujith@142
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chinthaginjalasujithkumar@gmail.com
spring.mail.password=wkag ewgs vvbs cuve
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
